clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  build:
    image: node:12-alpine
    commands:
      - npm install
      - npm run build
    when:
      event: [push, tag, pull_request]

  selenoid_website_latest_image:
    image: plugins/docker
    registry: registry.aerokube.com
    repo: registry.aerokube.com/selenoid/website
    secrets: [ docker_username, docker_password ]
    tags: [ 'latest' ]
    when:
      branch: master
      event: push

  selenoid_website_release_image:
    image: plugins/docker
    registry: registry.aerokube.com
    repo: registry.aerokube.com/selenoid/website
    secrets: [ docker_username, docker_password ]
    tags: [ '${DRONE_TAG}', 'latest-release' ]
    when:
      event: tag

  selenoid_website_push:
    image: golang:1.12.5
    commands:
      - export WD=$(pwd)
      - export CLONE_DIR="/go/website"
      - git clone https://${GITHUB_TOKEN}@github.com/aerokube/selenoid.git $CLONE_DIR
      - cd $CLONE_DIR && git config user.name ${DRONE_COMMIT_AUTHOR} && git config user.email ${DRONE_COMMIT_AUTHOR_EMAIL}
      - cd $CLONE_DIR && git checkout gh-pages && cp -R $WD/dist/* $CLONE_DIR
      - cd $CLONE_DIR && git add --all && git commit -am "Documentation updated by ${DRONE_COMMIT_AUTHOR}" && git push origin HEAD:gh-pages
    secrets: [ github_token ]
    when:
      event: tag
